name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    name: Lint, Typecheck, Test & Build

    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Install dependencies
        run: npm install --frozen-lockfile
        shell: bash

      - name: Setup Playwright Browsers
        run: npx playwright install

      - name: Run linters
        run: npm run lint

      - name: Run typecheck
        run: npm run typecheck

      - name: Run unit tests
        run: npm run test

      - name: Build application
        run: npm run build
